figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allpearsonrho);
set(gca,'XTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[-1 1]);
title('Pearson rho');
xticklabel_rotate;
saveas(a,'pearsonrho.png');
%subplot(3,3,2);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allspearmanrho);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[-1 1]);
title('Spearman rho');
xticklabel_rotate;
saveas(a,'spearmanrho.png');
%subplot(3,3,3);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allkendallrho);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[-1 1]);
title('Kendall rho');
xticklabel_rotate;
saveas(a,'kendallrho.png');
%subplot(3,3,4);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allcossim);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[-1 1]);
title('Cosine sim');
xticklabel_rotate;
saveas(a,'cossim.png');
%subplot(3,3,5);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allavgfluxdiff);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[0 10]);
title('Avg flux diff');
xticklabel_rotate;
saveas(a,'avgfluxdiff.png');
%subplot(3,3,6);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,alluptakesens);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[0 1]);
title('Uptake sens');
xticklabel_rotate;
saveas(a,'uptakesens.png');
%subplot(3,3,7);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allreleasesens);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[0 1]);
title('Release sens');
xticklabel_rotate;
saveas(a,'releasesens.png');
%subplot(3,3,8);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allnumreleasing);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[0 50]);
title('Num releasing');
xticklabel_rotate;
saveas(a,'numreleasing.png');
%subplot(3,3,9);
figure('Position',[300, 300, 1200, 500]);a=bar(2:2:116,allnumzero);
set(gca,'xTickLabel',expressionarray2);
set(gca,'XTick',2:2:116);
set(gca,'Ylim',[0 10]);
title('Num zero');
xticklabel_rotate;
saveas(a,'numzero.png');
%exctokeep2={'EX_carn(e)','EX_crn(e)','EX_hom_L(e)','EX_sucr(e)','EX_thymd(e)','EX_udpgal(e)','EX_udpg(e)','EX_thyox_L(e)','EX_triodthy(e)','EX_ascb_L(e)','EX_dhap(e)',...
%'EX_thm(e)','EX_btn(e)','EX_glcur(e)','EX_gmp(e)','EX_imp(e)','EX_HC02191(e)','EX_HC02192(e)','EX_ncam(e)','EX_cmp(e)','EX_nac(e)','EX_pyrdx(e)',...
%'EX_anth(e)','EX_srtn(e)','EX_bilirub(e)','EX_gchola(e)','EX_tchola(e)','EX_tdchola(e)','EX_chol(e)','EX_pchol_hs(e)','EX_glyb(e)','EX_sprm(e)','EX_gthox(e)','EX_lcts(e)',...
%'EX_ancys(e)','EX_34hpp(e)','EX_4abut(e)','EX_acac(e)','EX_ade(e)','EX_adn(e)','EX_akg(e)','EX_amp(e)','EX_cit(e)','EX_citr_L(e)','EX_creat(e)','EX_cytd(e)',...
%'EX_dad_2(e)','EX_dcyt(e)','EX_duri(e)','EX_hxan(e)','EX_ins(e)','EX_lac_L(e)','EX_lac_D(e)','EX_mal_L(e)','EX_orn(e)','EX_orot(e)','EX_oxa(e)',...
%'EX_ppa(e)','EX_pyr(e)','EX_sbt_D(e)','EX_spmd(e)','EX_succ(e)','EX_taur(e)','EX_thym(e)','EX_ump(e)','EX_ura(e)','EX_urate(e)','EX_uri(e)','EX_cit(e)','EX_glyc(e)'};