KPKpep=.31;
LPK=1000;
catp=4.27;
KPKatp=22.5;
cfdp=.272;
KPKfdp=.19;
camp=.9547;
KPKamp=.2;
cpep=2.67;
nPK=4;
cadp=.582;
KPKadp=.26;
rmaxPK=.0611;
crib5p=.398;
rateoriginalnumerator=rmaxPK*cpep*(cpep/KPKpep+1)^(nPK-1)*cadp;
rateoriginalinhibitionterm=((1+catp/KPKatp)/(cfdp/KPKfdp+camp/KPKamp+1))^nPK;
rateoriginal=rateoriginalnumerator/(KPKpep*(LPK*rateoriginalinhibitionterm+(cpep/KPKpep+1)^nPK)*(cadp+KPKadp));
rateoriginalrib5parray=[];
for i=5:-1:-5
    rateoriginalrib5pinhibitionterm=((1+catp/KPKatp)/(10^(i)*crib5p+cfdp/KPKfdp+camp/KPKamp+1))^nPK;
    raterib5parray(-i+6)=rateoriginalnumerator/(KPKpep*(LPK*rateoriginalrib5pinhibitionterm+(cpep/KPKpep+1)^nPK)*(cadp+KPKadp));
end
rateoriginalrib5pdiffsarray=rateoriginalrib5parray-rateoriginal;
rateoriginalrmaxfactor=rateoriginalrib5parray./rateoriginal;
Vmpfk=rmaxPK;
cpep=2.67;
cpyr=2.67;
catp1000s=4.0;
cpep1000s=2.86;
cpyr1000s=2.67;
cadp1000s=.58;
Kmpkf=cpep1000s*cadp1000s
Kmpkr=cpyr1000s*catp1000s
crib5p1000s=.4088;
Kapkrib5p=crib5p1000s;
Kapkrib5p=.004;
KMpkf=.0088;
KMpkr=.178;
Vmprk=.1972*2.5*cpep*cadp/Kmpkf*Kmpkr/(cpyr*catp)
alexfactorrib5p=((2.5*cpep*cadp/Kmpkf-Vmprk*cpyr*catp/Kmpkr)*crib5p/(1+cpep*cadp/Kmpkf+0*cpyr*catp/Kmpkr))/(Kapkrib5p+crib5p)
%rateoriginalAlexrib5ptest=(((Vmpfk*cpep*cadp/Kmpkf)*crib5p/(1+cpep*cadp/Kmpkf+cpyr*catp/Kmpkr))/(Kapk+crib5p))*(rmaxPK*cpep*(cpep/KPKpep+1)^(nPK-1)*cadp)/(KPKpep*(LPK*((1+catp/KPKatp)/(cfdp/KPKfdp+camp/KPKamp+1))^nPK+(cpep/KPKpep+1)^nPK)*(cadp+KPKadp));
%rateoriginalAlexrib5p=(((Vmpfk*cpep*cadp/Kmpkf-Vmprk*cpyr*catp/Kmpkr)*crib5p/(1+cpep*cadp/Kmpkf+cpyr*catp/Kmpkr))/(Kapk+crib5p))*(rmaxPK*cpep*(cpep/KPKpep+1)^(nPK-1)*cadp)/(KPKpep*(LPK*((1+catp/KPKatp)/(cfdp/KPKfdp+camp/KPKamp+1))^nPK+(cpep/KPKpep+1)^nPK)*(cadp+KPKadp));
%rateoriginal.*rmaxfactor-raterib5parray;
%KPKpep*(LPK*((1+catp/KPKatp)/(cfdp/KPKfdp+camp/KPKamp+1))^nPK+(cpep/KPKpep+1)^nPK)*(cadp+KPKadp)
%(1+catp/KPKatp)/(cfdp/KPKfdp+camp/KPKamp+1)
%(1+catp/KPKatp)/(.0001*crib5p+cfdp/KPKfdp+camp/KPKamp+1)
%10000*crib5p+cfdp/KPKfdp+camp/KPKamp+1
%(rmaxPK*cpep*(cpep/KPKpep+1)^(nPK-1)*cadp)/(KPKpep*(LPK*((1+catp/KPKatp)/(10000*crib5p+cfdp/KPKfdp+camp/KPKamp+1))^nPK+(cpep/KPKpep+1)^nPK)*(cadp+KPKadp))
